version: '3'

services:
  webollama:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ghcr.io/dkruyt/webollama:latest
    container_name: webollama
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - webollama-network

networks:
  webollama-network:
    name: webollama-network
