version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - ollama-network

  webollama:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ghcr.io/dkruyt/webollama:latest
    container_name: webollama
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    restart: unless-stopped
    depends_on:
      - ollama
    networks:
      - ollama-network

volumes:
  ollama_data:
    name: ollama_data

networks:
  ollama-network:
    name: ollama-network